@startuml ClassDiagram
'Moderation 
enum ModerationStatus{
    PendingReview,
    Active,
    Deactivated
}

class DeactivationRecord{
  +int gigId  ' nullable
  +string userId ' nullable
  +string reason
  +DateTime createdAt
}

class ReportedItem{
  +int gigId  ' nullable
  +string userId ' nullable
  +string reportedById
  +string reason
  +DateTime reportedAt
}




'Categories
class MainCategory {
  +String name
  +String description
  +List<SubCategory> subCategories
  +List<FAQ> faqs
}

class SubCategory {
  +String name
  +String imageURL
  +long mainCategoryId
  +List<SubSubCategory> subSubCategories
}

class SubSubCategory {
  +String name
  +long subCategoryId
  +List<Gigs> gigs
  +List<GigFilter> gigFilters
}

enum GigFilterType {
    DeliveryTime,
    PriceRange,
    SellerDetails,
    ServiceIncludes
}

class GigFilter {
  +String? title
  +GigFilterType type
  +List<FilterOption> options
}

class FilterOption {
  +String name
  +long gigFilterId
}

class FAQ {
    +String question
    +String answer
    +long mainCategoryId  ' nullable 
    +long gigId           ' nullable 
    +long userId          ' nullable
}




'Messaging
class Conversation{
  +String buyerId
  +String sellerId
  +DateTime createdAt
  +DateTime lastMessageAt
  +boolean isStarredByBuyer
  +boolean isStarredBySeller
  +int? gigId
  +List<Message> messages
}

class Message{
  +String text
  +DateTime sentAt
  +long conversationId
  +String senderId
  +String receiverId
  +String photoURL 'nullable
  +boolean isRead
  +long? customOfferId
  +long? customRequestId
  +long? deliveryId
  +long? revisionId
}



'Orders
enum OrderStatus {
    PlacedOrder,
    SubmittedRequirements,
    Pending,
    InProgress,
    Delivered
}

class OrderDeliveryDate{
  +long orderId
  +DateTime deliveryDate
  +boolean isDeliveryDateChanged
  +string changeDateReason 'nullable
}

class Order{
  +String orderNumber
  +long gigId  'nullable
  +long customOfferId  'nullable
  +long selectedPaymentPlanId  'nullable
  +String buyerId
  +DateTime createdAt
  +DateTime deliveredAt   'nullable
  +OrderStatus status
  +List<Review> reviews  'nullable
  +long conversationId  'nullable
  +List<Revision> revisions  'nullable
  +List<GigRequirementAnswer> gigRequirementAnswers  
  +long invoiceId  'nullable
  +long deliveryId  'nullable
}

class GigRequirementAnswer{
  +long id
  +String answer
  +long gigRequirementId
  +long orderId
  +List<String> fileUrls
}

class Review{
  +long id
  +String comment
  +int rating
  +DateTime createdAt
  +long orderId
  +String creatorId
}

class Invoice{
  +long id
  +long orderId
  +String invoiceNumber
  +DateTime createdAt
  +double tax
  +double amount
}

enum RevisionStatus {
    Pending,
    Accepted,
    Rejected
}

class Revision{
  +int id
  +String description
  +int orderId
  +DateTime createdAt
  +DateTime? acceptedAt
  +DateTime? rejectedAt
  +RevisionStatus status
  +String? rejectionReason 'nullable
  +List<string> attachmentUrls 'nullable
  +string?  sourcefileUrl
}

class Delivery{
  +int id
  +String description
  +int orderId
  +DateTime createdAt
  +DateTime? acceptedAt
  +List<string> attachmentUrls 'nullable
  +string? sourcefileUrl
}



'Custom Offers
enum CustomOfferStatus {
    Pending,
    Accepted,
    Rejected,
    Withdrawn,
    Expired
}

class CustomOffer{
  +long id
  +String description
  +double price
  +int revisions
  +int deliveryTimeInDays
  +long conversationId
  +long gigId
  +String sellerId
  +String customOfferNumber
  +String buyerId
  +CustomOfferStatus status
  +DateTime createdAt
  +String rejectionReason 'nullable
  +String withdrawalReason 'nullable
  +List<SubSubCategoryFilter> selectedFilters
  +DateTime acceptedAt 'nullable
  +DateTime rejectedAt 'nullable
  +DateTime expiredAt 
  +long customRequestId  'nullable
  +long projectBriefId 'nullable
}




'Gigs
class GigMetadata{
  +long filterOptionId
  +long gigId
}

class GigRequirement{
  +String question
  +long gigId
  +boolean isFileUpload
}

class PaymentPlan{
  +String name
  +double price
  +long gigId
  +int deliveryTimeInDays
  +int revisions
  +String description
  +List<PaymentPlanInclude> inclusions
}

class PaymentPlanInclude{
  +String name
  +String value
  +long paymentPlanId
}

class Gig{
  +String title
  +String description
  +String sellerId
  +String mainCategoryId
  +long subCategoryId
  +long subSubCategoryId
  +ModerationStatus moderationStatus
  +List<FAQ> faqs
  +List<GigMetadata> metadata
  +List<GigRequirement> requirements
  +List<PaymentPlan> paymentPlans
  +List<String> imageURLs
  +string videoURL 'nullable
  +List<Tag> tags
  +List<Order> orders 'nullable
  +List<CustomOffer> customOffers 'nullable
  +List<CustomRequest> customRequests 'nullable
}

class Tag{
  +String name
  +long gigId
}


'Common
interface IBaseEntity<TId> {
    +TId id    
    +Boolean isDeleted
    +DateTime? deletedAt 
}

class BaseEntity  {
    +TId id   
    +DateTime isDeleted
    +DateTime deletedAt   'nullable
}

interface ISoftDelete {
    +Boolean isDeleted
    +DateTime? deletedAt 
}

BaseEntity -|> IBaseEntity
BaseEntity -|> ISoftDelete



' Users
class ApplicationUser{
  +List<Notification> notifications   'nullable
  +List<Conversation>? conversations  'nullable
  +List<FAQ> faqs       'nullable
  +String description    'nullable
  +String fullName     'nullable
  +Address? address    'nullable
  +ModerationStatus moderationStatus
  +DateTime joinedAt
  +string photoURL      'nullable
  +List<UserLanguage> userLanguages   'nullable
  +List<Reviews> reviews    'nullable
  +List<Order>? orders  'nullable
  +List<CustomOffer>? customOffers'nullable
  +List<ProjectBrief>? projectBriefs'nullable
}

class Buyer{
  +String applicationUserId
  +List<Invoice>? invoices
  +int? billingDetailsId
  +List<FavouriteGigsList>? favoriteGigsList
  +List<BrowsingHistory>? browsingHistoryGigs
}

class FavouriteGigsList{
  +int id
  +String buyerId
  +List<FavouriteGig> favouriteGigs
  +DateTime createdAt
  +String description
  +String name
}

class FavouriteGig{
  +long id
  +String buyerId
  +long gigId
  +DateTime addedAt
  +long favouriteGigsListId
}

class BrowsingHistory{
  +int id
  +String userId
  +long gigId
  +DateTime viewedAt
}

class Address{
  +int id
  +String country
  +String city
  +String street
  +String zipCode
  +String userId  
  +boolean isBillingAddress
}

class BillingDetails{
  +String fullName  
  +Address billingAddress
  +int billingAddressId
  +String? companyName
}

class Seller{
  +String applicationUserId
  +List<Gig>? gigs
  +List<Certification>? certifications
  +List<Education>? educations
  +List<Skill>? skills
  +List<Portfolio>? portfolios
}

enum SkillLevel {
    Beginner,
    Intermediate,
    Advanced
}

class Skill{
  +int id
  +String name
  +SkillLevel level
  +int sellerId
}

enum ProficiencyLevel {
    Basic,
    Conversational,
    Fluent,
    Native
}

class Language{
  +int id 
  +String name 
}

class UserLanguage{
  +int languageId
  +ProficiencyLevel proficiencyLevel
  +string userId
}

enum EducationDegree{
    HighSchool,
    Bachelors,
    Masters,
    PhD
}

class Education{
  +String institution
  +EducationDegree degree
  +DateTime startDate
  +DateTime endDate
  +int sellerId
}

class Certification{
  +String name
  +String issuer
  +DateTime issuedAt
  +string sellerId
}

class Portfolio{
  +String title
  +String description
  +String List<imageURL>
  +int sellerId
  +String videoURL 'nullable
}

class Notification{
  +String title
  +String message
  +DateTime createdAt
  +String userId
  +boolean isRead
  +NotificationType type
}

enum NotificationType{
  ProfileUpdate,
  ProfileMade,
  OrderStatusUpdate,
  OrderPlaced,
 OrderDelivered,
 RevisionREceived,
 CustomOfferReceived,
 CustomRequestReceived,
 NewProjectBrief,
 ProjectBriefReceived,
 CustomOfferAccepted,
 CustomOfferExpired,
 CustomOfferCanceller,
 NewGig
}



'Custom Requests
enum CustomRequestStatus {
    Pending,
    Accepted,
    Rejected,
    Withdrawn
}

class CustomRequest{
  +String description
  +String buyerId
  +int gigId
  +DateTime createdAt
  +DateTime? acceptedAt
  +DateTime? rejectedAt
  +String rejectionReason 'nullable
  +decimal budget
  +int deliveryTimeInDays
  +string customRequestNumber
  +List<String> photoURL 'nullable
}




'Project Briefs
enum ProjectBriefStatus {
    Pending,
    OrderPlaced,
    Delivered,
    Cancelled
}

class ProjectBrief{
  +String description
  +String aboutBuyer
  +int buyerId
  +DateTime createdAt
  +DateTime? closedAt
  +ProjectBriefStatus status
  +decimal budget
  +int deliveryTimeInDays
  +string projectBriefNumber
  +int? mainCategoryId
  +int? subCategoryId
  +List<CustomOffer>? customOffers
}



@enduml
